[project]
name = 'Crowdfunding-Grant-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.campaign-management]
path = 'contracts/campaign-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.contribution-nft]
path = 'contracts/contribution-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.disbursement]
path = 'contracts/disbursement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
